create table stringfunc(num int, name varchar(30),salary float)
select * from stringfunc
select ASCII('A')
select CHAR(113)
select ltrim('    hello')
select rtrim('hello    ')
select LOWER('SAMPATH')
select UPPER('Sampath')
select REVERSE('Cognine')
select LEN('sampath  ')
select LEFT('ABCDE',3)
select RIGHT('ABCDE',2)
select CHARINDEX('@','sampath@cognine',1)
select SUBSTRING('sam@cognine',5,11)